### ISSUE TITLE
can't find my env var on VM after deployment 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/terraform-provider-grid#113]
deployed a VM with env variable:
```
env_vars {
      key = "TEST_VAR"
      value = "this value for test"
    }
```
and try to ssh VM and printenv or echo $TEST_VAR but not found
main.tf: https://gist.github.com/mhost39/b692447d30f731a0af569de55c74fe75

**Comment by OmarElawady** [comment]
This looks like a dropbear thing. The image you are using is using dropbear, a lightweight ssh server, instead of openssh. The environment variables are stored correctly in `/etc/environment` but dropbear doesn't pick them up,

I tried with a different [image](https://hub.grid.tf/omar0.3bot/omarelawady-ubuntu-20.04.flist) which uses openssh and the environment variables appeared in the ssh session.

**Comment by mhost39** [comment]
it worked fine with anther image uses openssh

**Comment by xmonader** [comment]
@muhamadazmy this means our official base isn't working okay
