### ISSUE TITLE
Increasing IP workloads in a deployment doesn't work (affects K8s and deployments)

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/terraform-provider-grid#15]
## Description

There's no way to change the number of IPs when updating a contract. Which causes the deployments to fail if it requires more public IPs than it initially requested.

## Reporting in the plugin

Fails with proper message

## Workaround

destroy the resource and re-create it.

`terraform destroy -target <resource name> -parallelism=1 && terraform apply -target <resource name> -parallelism=1`

## Fixes

Wait for https://github.com/threefoldtech/zos/issues/1366

**Comment by MarioBassem** [comment]
currently, solving this would require lots of changes, since the provider is designed to maintain a single deployment per node, and since updating number of public ips for a contract is not yet supported, the only solution is to create a new contract with the updated number of ips, and delete the old contract. but this behavior is undesired since a user may have important data on the deleted deployment.

**Comment by ashraffouda** [comment]
not supported by zos https://github.com/threefoldtech/zos/issues/1366
