### ISSUE TITLE
trim inputs 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/terraform-provider-grid#159]
recently this happened

![image](https://user-images.githubusercontent.com/64129/147952130-34793a5f-0374-408a-9cac-9eb823d05235.png)

which caused by having a leading space in the IP input field

**Comment by OmarElawady** [comment]
The state should match the file to avoid terraform detecting a change and firing an unnecessary and confusing update because a space is added. The state is updated from remote and since the remote stores it trimmed it would update the state without state causing the unnecessary update to happen. A check with a friendly message is added to avoid this.
