### ISSUE TITLE
VM is not found after deployment

### ISSUE THREAD

**Issue by Zurga** [threefoldtech/terraform-provider-grid#195]
I am trying to deploy a VM to the grid, using the following configuration:

```hcl
resource "grid_deployment" "d1" {
    node = 301
    network_name = grid_network.net.name
    ip_range = lookup(grid_network.net.nodes_ip_range, 301, "")
    disks {
        name = "data"
        size = 10
    }
    vms {
        name = "vm1"
        flist = "https://hub.grid.tf/tf-official-vms/ubuntu-20.04-latest.flist"
        cpu = 1
        planetary = true
        memory = 1024
        env_vars = {
            SSH_KEY = "redacted"        
        }
        mounts {
            disk_name = "data"
            mount_point = "/test/blac"
        }
    }
}
```
I am getting the following error however:
```
╷
│ Error: error waiting deployment: workload 0 failed within deployment 632 with error : failed to find vm with id '2758-632-vm1': vm '2758-632-vm1' not found
│ 
│   with grid_deployment.d1,
│   on main.tf line 21, in resource "grid_deployment" "d1":
│   21: resource "grid_deployment" "d1" {
│ 
╵
```
This is new, this deployment worked fine 5 minutes before...

**Comment by OmarElawady** [comment]
Are you sure you are using the correct flist url? The flist for the ubuntu image is `https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist`. The link you are using is for an flist with its own kernel and it's not well-tested afaik.

The error happens because the VM dies just after it starts, so its setup fails.

I tried this deployment with the given URL (official-apps not vms) and the deployment was successful

**Comment by Zurga** [comment]
Well that could be it, I found this flist on the Hub under `official VMS` so I assumed that it would working.
https://hub.grid.tf/tf-official-vms
