### ISSUE TITLE
Terraform - Error: failed to create contract: ContractIsNotUnique

### ISSUE THREAD

**Issue by luisanadal** [threefoldtech/terraform-provider-grid#264]
Hello,

I hit the below error when deploying multiple resources, if count is equal 1 then all good, otherwise fails

**_Error:_** 

```
grid_deployment.workers[0]: Creation complete after 59s [id=3370]
grid_deployment.workers[1]: Creating...
╷
│ Error: failed to create contract: ContractIsNotUnique
│ 
│   with grid_deployment.workers[1],
│   on test.tf line 29, in resource "grid_deployment" "workers":
│   29: resource "grid_deployment" "workers" {
│ 
```

**_Terraform configuration:_**
```
...
resource "grid_deployment" "workers" {
  count = 2  
  vms {
    name = "${format("vm_test_%01d",count.index+1)}"
    flist = "https://hub.grid.tf/tf-official-vms/ubuntu-18.04-lts.flist"
    publicip = false
    planetary = true
    cpu = 2
   ... 
  }
  ....
}

 resource "null_resource" "workers" {
  depends_on = [grid_deployment.workers]
  count      = length( grid_deployment.workers)

   provisioner "file" {
     source      = "./setup.sh"
     destination = "/tmp/setup.sh"
   }
   provisioner "remote-exec" {
     inline = [
       "chmod +x /tmp/setup.sh",
       "/tmp/setup.sh",
     ]
   }
   connection {
     type        = "ssh"
     user        = "root"
     password    = ""
     private_key = "${file("~/.ssh/id_rsa")}"
     host = grid_deployment.workers[count.index].vms[0].ygg_ip
   }
 }
```

**Comment by ramezsaeed** [comment]
@muhamadazmy @OmarElawady

**Comment by OmarElawady** [comment]
As described in the [limitation](https://github.com/threefoldtech/terraform-provider-grid#current-limitation) section, it's not allowed to have multiple deployments on different nodes. So even if it works, it would cause the private network to have conflicts.

This error happens when a contract with the same data is already active. It seems from the issue description that the two conflicting contracts are not in the same deployment (one in the new deployment, and an old one). Can you try to change the data on the main.tf file to make sure it's (not) a self-conflicting terraform deployment, and provide a full main.tf file reproducing the issue if it still happens?
