### ISSUE TITLE
Long-living substrate clients gets closed and is not reconnected

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/terraform-provider-grid#277]
The substrate connection currently is shared on a single resource operation. When this operations takes a long time, any substrate operation fails with an error like ("use of a closed connection"). This should probably be resolved in substrate-client, but on our end the manager should live on objects and substrate clients generated on demand instead of getting passed around.

**Comment by mohamedamer453** [comment]
Verified on devnet.

first a connection was made to the substrate client then and an operation to return the twin id, and then the client was put to sleep for 5 mins before performing the same operation again. and during this time the client was working and didn't return any errors.

![image](https://user-images.githubusercontent.com/101194226/187714762-f7f4782c-dc42-492e-b75d-5ce079e01f63.png)

and to ensure that it's really working i tried the same operations performed above on an older version of the client and after sleeping for 5 mins it returned 0 instead of the actual id of the twin.

![image](https://user-images.githubusercontent.com/101194226/187716880-05cad292-2671-4110-b867-e6ba1d6146db.png)
