### ISSUE TITLE
deployment fails in single node and k8s scripts

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#354]
### tested on devnet

**test made to produce**

**single node**
1. open terraform
2. go to the single node script
3. `cd /examples/resources/singlenode`
4. choose node from devnet
5. run `terraform init && terraform apply -parallelism=1`
6. deployment will fail
![Screenshot from 2022-11-15 17-04-10](https://user-images.githubusercontent.com/110984055/201953056-da659db3-8a32-4094-94cd-408648a11548.png)

**k8s**

1. open terraform
2. go to the single node script
3. `cd /examples/resources/k8s`
4. choose node from devnet
5. run `terraform init && terraform apply -parallelism=1`
6. deployment will fail because of the source
![Screenshot from 2022-11-15 16-57-45](https://user-images.githubusercontent.com/110984055/201953370-d0fb8acb-fd8b-4447-bdca-32cfcca4ccb9.png)

**Comment by MarioBassem** [comment]
the error in single node deployment says that it's not finding .terraform.tfstate.lock.info file. maybe because there was an old deployment that you are trying to overwrite? 
maybe make sure that before executing ```terraform init``` you've removed all terraform state files and directories, and after ```terraform init``` make sure that the state files are intact.
anyway, the examples are updated here (https://github.com/threefoldtech/terraform-provider-grid/pull/362) and will be released in v1.5.9
