### ISSUE TITLE
chagnes to gatwayes deployer sync method

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/terraform-provider-grid#401]
Currently the sync method checks only for contracts whether they're found and in a created state, If any of these are not true contract gets deleted (only in the deployer). Now that contracts are separate than deployments should the method check for contracts and deployments and on what condition should contracts be deleted?

If it should check for deployments too what condition will make it valid knowing that deployments don't have state? just that they exist?

**Comment by MarioBassem** [comment]
i think resource should never try to manipulate capacity contracts, it's not their job. 
And for the validation part, since we have an additional layer, maybe we should add it's validation also. 
meaning that for the resource to do it's work correctly it needs a valid capacity contract and a valid deployment if there is any. So i think we should validate both, and inform the user if something looks wrong before trying to do any modifications to the state.

**Comment by AbdelrahmanElawady** [comment]
After discussions with @MarioBassem we thought it would be best to check for both deployments and contracts and return detailed errors to the user if they aren't valid.

Now the issue is what to do with CapacityDeploymentMap (map from capacity contract ID to deployment ID):
- remove the contract ID entry from the map: the user might be able to deploy again but will lose the invalid deployment ID so they won't be able to cancel it and may take some of the resources of the capacity contract.
- leave the map unchanged: the user probably won't be able to deploy again but they will have the invalid deployment ID and can delete it manually and then make another deployment.

**Comment by MarioBassem** [comment]
this issue was related to the new power management changes and is now obsolete.
