### ISSUE TITLE
Capacity planner only within dedicated nodes

### ISSUE THREAD

**Issue by Nelson361** [threefoldtech/terraform-provider-grid#496]
The capacity planner searches the entire network. Solution providers use dedicated nodes to be profitable. By restricting the capacity planner to dedicated nodes reserved by the user, the solution provider can automatically deploy to his nodes. This could be as fancy as searching for the dedicated nodes associated with the seed phase, or simply restricting the search to a set of nodes that is entered in the terraform template.

**Comment by MarioBassem** [comment]
after scheduler's latest update (https://github.com/threefoldtech/terraform-provider-grid/pull/563), a user could now search for rentable nodes, and also could exclude specific nodes from their search.

**Comment by rkhamis** [comment]
I think here we should favor dedicated nodes if a user has any. the capacity filter should pick of them first

**Comment by ashraffouda** [comment]
> I think here we should favor dedicated nodes if a user has any. the capacity filter should pick of them first

if the user has a dedicated node and wants to deploy on he can still specify the node, otherwise if he decided to use the scheduler  then he will get a random node

**Comment by ashraffouda** [comment]
the current implementation of grid proxy returns all matched nodes ids without sorting it. so to get the dedicated nodes of a user is costly, hence it requires to loop over all nodes and check if it is dedicated or not. so we will stop working on this until this issue is done in grid proxy 
https://github.com/threefoldtech/tfgridclient_proxy/issues/311
