### ISSUE TITLE
wireguard test fails

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#769]
### description 
wire guard test fails and gets stuck

![image](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/aefda1ce-3283-4912-90c6-021036c596db)

**Comment by AbdelrahmanElawady** [comment]
the error is coming from executing this line:
```go
_, err = exec.Command("wg-quick", "up", f.Name()).Output()
```

do you have wireguard installed? and if so can you run `wg-quick up` with the file created during the test manually?

**Comment by rawdaGastan** [comment]
Tested the wireguard test after fix and it worked (maybe wg is not working on your machine)
- https://github.com/threefoldtech/terraform-provider-grid/actions/runs/7287811183

1. It worked for dev, qa, test
2. It failed in mainnet because of availableFor filter of the nodes (will be solved in the next mainnet release)

**Comment by Eslam-Nawara** [comment]
Verified:
Working well according to the [workflow](https://github.com/threefoldtech/terraform-provider-grid/actions/runs/7287811183)
