### ISSUE TITLE
support zos4 deployments 

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#975]
### Describe the solution you'd like
zos4 now have different workload typs than zos3 
it has networklight instead of network amd zmachine_light instead of zmachine
  - [network light](https://github.com/threefoldtech/zos/blob/zos-light/pkg/gridtypes/zos/network_light.go)
  - [zmachine light](https://github.com/threefoldtech/zos4/blob/main/pkg/gridtypes/zos/network_light.go)

also zos4 nodes doesn't support wireguard, ygg and public config stuff

**Comment by SalmaElsoly** [comment]
## Verification Steps:
- tried to deploy a vm using this script https://github.com/threefoldtech/terraform-provider-grid/blob/development/integrationtests/vm/main.tf
- deployed light network and machine since there is no yggdrasil or wireguard required

### Successfully deployed
![image](https://github.com/user-attachments/assets/b0aa6c6d-4cc9-4bd4-8ba2-150aabd00ec6)

### Listed in dashboard
![image](https://github.com/user-attachments/assets/7fabe270-a10f-40d9-94ef-daa05cc6ddeb)

### Successfully ssh to the vm
![image](https://github.com/user-attachments/assets/c151c22a-75bb-4ceb-9730-69a1d9e3309b)
